name: CI - Code Security & Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-check:
    name: Scan Secrets and Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git -v

  build:
    name: Archive Static App
    runs-on: ubuntu-latest
    needs: security-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Archive static files
        uses: actions/upload-artifact@v4
        with:
          name: static-app
          path: |
            index.html
            *.css
            *.js
